# Generated by Django 3.1.3 on 2020-11-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_auto_20201116_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='label_id',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher_id',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='series_id',
            new_name='series',
        ),
    ]
