# Generated by Django 3.1.3 on 2020-11-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0004_auto_20201116_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='how_to_read',
        ),
        migrations.AddField(
            model_name='author',
            name='family_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='test', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='given_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
